var splashList = [
  "while you wait, why don't you go pet a dog?<br>injest cyanide?<br>replace your sister's insulin with heroin?",
  "did you know? 100% of people reading this are mentally retarded.",
  "what?<br>what are you looking at?<br>cmon bro what's up<br>okay buddy<br>guess i have no choice but to let you go on to your chat...",
  "if one out of two hoes are mad and i'm not mad...<br><i>hoes mad.",
  "imagine having so few friends you're<br>chillin' on achat...",
  "splash screens! i hope you appreciate i had to type every single one of these out.",
  "there's no way in hell<br>im letting you pass<br><i>without even reading this.",
  "when life gets hard,<br><b>go soft.",
  "someone once told me if you send me nudes<br>you'll get a free ice cream sundae",
  "the best thing to do in the morning is go<br>right the fuck back to sleep",
  "don't talk to me until i've done my morning<br>cocaine, and then,<br><b>still don't talk to me",
  "look mom, just because i have no friends and write<br>splash screens for achat doesn't mean i'm lonely",
  "i bet you kiss girls, faggot",
  "i always give 110% effort,<br>and that explains why i failed math",
  "hey hey hey, shutting the fuck up is vegan friendly<br><i>just thought you should add that to your diet",
  "Jesus said, 'Are you being willfully stupid?'<br>- Mark 7:18",
  "do you genuinely look at these?<br>or am i just wasting my time?",
  "sorry this wait is so long, firebase and async calls is retarded",
  "hey retard<br><b>manual breathing",
  "hey retard<br><b>manual blinking",
  "hey retard<br><b>your tounge doesn't fit in your mouth",
  "make sure not to use profanity on achat<br>mommy said that's not allowed",
  "feeling down? depressed? sad?<br>1-800-273-8255<br>this isn't even a joke suicide and<br>depression are serious issues",
  "how's you day been so far?",
  "oh my fucking GOD this is taking so long to write so many splash screens",
  "please dear god if nobody likes these i'm offing myself"
]